name: Queue Wiki Generation

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]
    paths: [ '*.md', 'wiki/*.md' ]
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes to process tasks

jobs:
  # Job 1: Find wiki links and create tasks (runs on file changes)
  create-tasks:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history to determine changes
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fire loguru gh-store duckduckgo_search PyGithub
    
    - name: Find changed markdown files
      id: changed-files
      uses: tj-actions/changed-files@v37
      with:
        files: |
          **/*.md
    
    # - name: Create wiki tasks for changed files
    #   if: github.event_name == 'push'
    #   run: |
    #     echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
    #     python scripts/create_wiki_tasks.py process_changed_files ${{ steps.changed-files.outputs.all_changed_files }}
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Create wiki tasks for all files (manual trigger)
    #   if: github.event_name == 'workflow_dispatch'
    #   run: |
    #     # Process all markdown files
    #     find . -type f -name "*.md" 
    #     find . -type f -name "*.md" | xargs python scripts/create_wiki_tasks.py process_changed_files --root_dir="." --output_dir="wiki"
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: Create wiki tasks for changed files
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
        files="${{ steps.changed-files.outputs.all_changed_files }}"
        # Process each file individually
        for file in $files; do
          python scripts/create_wiki_tasks.py process_file "$file" --root_dir="." --output_dir="wiki"
        done

    - name: Create wiki tasks for all files (manual trigger)
      if: github.event_name == 'workflow_dispatch'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Process all markdown files individually
        find . -type f -name "*.md" | while read file; do
          python scripts/create_wiki_tasks.py process_file "$file" --root_dir="." --output_dir="wiki"
        done


  # # Job 2: Process pending wiki tasks (runs on schedule or manual trigger)
  # process-tasks:
  #   if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
  #   runs-on: ubuntu-latest
  #   permissions:
  #     issues: write
  #     contents: write
    
  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v4
  #     with:
  #       token: ${{ secrets.GITHUB_TOKEN }}
    
  #   - name: Set up Python
  #     uses: actions/setup-python@v5
  #     with:
  #       python-version: '3.12'
    
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install fire loguru gh-store duckduckgo_search PyGithub
    
  #   - name: Process pending wiki tasks
  #     run: |
  #       # List pending tasks (for logging)
  #       python scripts/process_wiki_tasks.py get_tasks --limit 10
        
  #       # Process tasks
  #       python scripts/process_wiki_tasks.py process --limit 5
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #   - uses: stefanzweifel/git-auto-commit-action@v5
  #     with:
  #       commit_message: "chore: expanded wiki"
