name: Auto Wiki Generation

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]
    paths:
      - '**.md'
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes to process tasks

jobs:
  # Job 1: Find wiki links and create tasks (runs on file changes)
  create-tasks:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history to determine changes
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fire loguru gh-store duckduckgo_search PyGithub
    
    - name: Find changed markdown files
      id: changed-files
      uses: tj-actions/changed-files@v37
      with:
        files: |
          **/*.md
    
    - name: Create wiki tasks for changed files
      if: github.event_name == 'push'
      run: |
        echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
        python scripts/create_wiki_tasks.py process_changed_files ${{ steps.changed-files.outputs.all_changed_files }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create wiki tasks for all .md files (manual trigger)
      if: github.event_name == 'workflow_dispatch'
      run: |
        # Find and process all non-wiki markdown files
        find . -type f -name "*.md" -print0 | xargs -0 python scripts/create_wiki_tasks.py process_changed_files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Job 2: Process pending wiki tasks (runs on schedule or manual trigger)
  process-tasks:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Process pending wiki tasks
      run: |
        # List pending tasks (for logging)
        python scripts/process_wiki_tasks.py get_tasks --limit 10
        
        # Process tasks
        python scripts/process_wiki_tasks.py process --limit 5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Commit wiki changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Wiki Bot"
        
        # Check if wiki directory exists
        if [ -d "wiki" ]; then
          # Check if there are changes to commit
          git add wiki/
          git status --porcelain wiki/ | grep -q "^M"
          
          if [ $? -eq 0 ]; then
            # Changes detected
            git commit -m "Auto-generate wiki content [skip ci]"
            git push
          else
            echo "No wiki changes to commit"
          fi
        else
          echo "Wiki directory not found"
        fi
