name: Auto Wiki Generation

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]
    paths:
      - '**.md'
      - '!wiki/**.md'  # Don't trigger on wiki files
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'
      - '!wiki/**.md'
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes to process tasks

jobs:
  # Job 1: Find wiki links and create tasks (runs on file changes)
  create-tasks:
    if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history to determine changes
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Find changed markdown files
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      id: changed-files
      uses: tj-actions/changed-files@v37
      with:
        files: |
          **/*.md
          **/*.markdown
          !wiki/**/*.md
    
    - name: Create wiki tasks for changed files
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      run: |
        echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
        python scripts/create_wiki_tasks.py process_changed_files ${{ steps.changed-files.outputs.all_changed_files }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create wiki tasks for all files (manual trigger)
      if: github.event_name == 'workflow_dispatch'
      run: |
        # Find and process all non-wiki markdown files
        find . -type f -name "*.md" -not -path "./wiki/*" -print0 | xargs -0 python scripts/create_wiki_tasks.py process_changed_files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Job 2: Process pending wiki tasks (runs on schedule or manual trigger)
  process-tasks:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Ensure directories exist
      run: |
        mkdir -p wiki
        mkdir -p prompts
        
        # Create default system prompt if it doesn't exist
        if [ ! -f "prompts/system_prompt.md" ]; then
          echo "Creating default system prompt"
          cat > prompts/system_prompt.md << 'EOF'
You are a wiki content creator that writes comprehensive, informative articles on various topics. Your task is to create a well-structured wiki page based on the provided search results.

Follow these guidelines when creating wiki content:

1. Begin with a clear, concise introduction that defines the topic.
2. Structure the content with appropriate headings (using Markdown # syntax).
3. Include relevant facts, history, context, and explanations from the search results.
4. Maintain a neutral, objective tone throughout.
5. Format the content using Markdown for readability.
6. Include internal wiki links in [[double brackets]] when referring to other potentially relevant topics.
7. Be comprehensive but concise - focus on the most important information.
8. If the search results contain conflicting information, acknowledge this and present the different perspectives.
9. End with a brief conclusion summarizing the key points.
10. If appropriate, include a "See Also" section with related topics formatted as [[wiki links]].

Your goal is to create a valuable reference article that would fit well in a knowledge wiki.
EOF
        fi
    
    - name: Process pending wiki tasks
      run: |
        # List pending tasks (for logging)
        python scripts/process_wiki_tasks.py get_tasks --limit 10
        
        # Process tasks
        python scripts/process_wiki_tasks.py process --limit 5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Commit wiki changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Wiki Bot"
        
        # Check if there are any changes to commit
        if git diff --quiet wiki/; then
          echo "No wiki changes to commit"
        else
          git add wiki/
          git commit -m "Auto-generate wiki content [skip ci]"
          git push
        fi
