name: Process Task(s)
on:
  issues:
    types: [opened, reopened]
  workflow_dispatch:
  schedule:
  - cron: '*/10 * * * *'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  process-task:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gh-store duckduckgo_search llamero
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          
      - name: Process Task
        if: contains(github.event_name, 'opened') && contains(github.event.issue.labels.*.name, 'task')
        run: |
          RESULT=$(python scripts/process_task.py --issue-number "$ISSUE_NUMBER")
          gh issue comment "$ISSUE_NUMBER" --body "$RESULT" --repo "$GITHUB_REPOSITORY"

          # TODO: use gh-store to update the issue state and be responsible for closing it
          #gh issue close "$ISSUE_NUMBER" --repo "$GITHUB_REPOSITORY"
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}

      - name: Process Task Queue
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          python scripts/process_pending_tasks.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

      # - name: Commit changes
      #   id: commit
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: "chore: Generated content"
      #     file_pattern: |
      #       wiki/*.md
